---
- name: "Run Docker-Compose using ansible playbook"
  hosts: localhost
  tasks:
  - name: stop and remove containers
    command: docker-compose down
    ignore_errors: yes
  
  - name: remove image built with dockercompose
    command: docker rmi -f mahmoudnabil70/nginx:alpine3.19
    ignore_errors: yes

  - name: build docker compose
    command: docker compose up --build -d
