---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:

    - name: build docker image using the Dockerfile
      command: docker build -t romofyi-html-image .

    - name: run container
      command: docker run -d --name web-container -p 8080:80 romofi-html-image

